import type { Metadata } from "next";
import { ABeeZee, Butterfly_Kids } from "next/font/google";
import "./globals.css";

const abeeze = ABeeZee({
  variable: "--font-abeeze",
  weight: ["400"],
});

const butterflyKids = Butterfly_Kids({
  variable: "--font-butterfly-kids",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${abeeze.variable} ${abeeze.className} ${butterflyKids.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
